import os
import re

# Path to the Docs directory
DOCS_DIR = os.path.dirname(os.path.abspath(__file__))

# Output JS file
OUTPUT_FILE = os.path.join(DOCS_DIR, '../docs-content.js')

# Map filename (without .content.html) to key in JS object
# e.g. object.content.html -> 'object'
def get_page_key(filename):
    return filename.replace('.content.html', '')

def html_to_js_string(html):
    # Escape backslashes, backticks, and newlines for JS template string
    html = html.replace('`', '\\`')
    return html

def main():
    content_files = [f for f in os.listdir(DOCS_DIR) if f.endswith('.content.html')]
    content_dict = {}
    for fname in content_files:
        key = get_page_key(fname)
        with open(os.path.join(DOCS_DIR, fname), 'r', encoding='utf-8') as f:
            html = f.read()
            content_dict[key] = html_to_js_string(html)

    # Write JS file
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as out:
        out.write('// Auto-generated by patch.py\n')
        out.write('window.DOCS_CONTENT = {\n')
        for i, (key, html) in enumerate(content_dict.items()):
            comma = ',' if i < len(content_dict) - 1 else ''
            out.write(f'  "{key}": `{html}`{comma}\n')
        out.write('};\n')

if __name__ == '__main__':
    main()
